name: CI

on:
  push:
    branches: [main, 'release/**']
  pull_request:
    branches: [main, 'release/**']
  workflow_dispatch:

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 8.9.0
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - run: pnpm install
      - run: pnpm turbo run format:check
      - run: pnpm turbo run lint
      - run: pnpm turbo run type-check
      - run: pnpm turbo run build