name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 8.9.0
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Check formatting
        run: pnpm turbo run format:check
        
      - name: Lint
        run: pnpm turbo run lint
        
      - name: Type check
        run: pnpm turbo run type-check
        
      - name: Build
        run: pnpm turbo run build