name: Preview Release

on:
  push:
    branches: [main]
    paths:
      - 'sdk/**'
      - 'mcp-server/**'
      - '!**.md'
      - '!**/*.test.ts'
      - '!**/TEST.md'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-preview:
    runs-on: ubuntu-latest
    if: !contains(github.event.head_commit.message, '[skip ci]')
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: pnpm/action-setup@v4
        with:
          version: 8.9.0
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          
      - run: pnpm install
      - run: pnpm turbo run build --filter=@amp-labs/*
      
      - name: Release Previews
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm -r --filter=@amp-labs/* exec semantic-release